
experiment_name: "ravdess_baseline_8class"

dataset:
  name: "ravdess"
  args:
    hf_id: "TwinkStart/RAVDESS"
    batch_size: 16
    num_workers: 16
    target_size: [244, 244] # Paper Size

model:
  name: "maxmvit_mlp"
  num_classes: 8 

training:
  epochs: 50
  lr: 0.0002 # Paper value (CRITICAL: 0.02)
  patience: 10
  seed: 42
  device: "cuda"
  scheduler:
    factor: 0.1
    patience: 3
    min_lr: 1e-6
  
paths:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
